### ISSUE TITLE
user defined plugin can not import

### ISSUE THREAD

**Issue by FrankCreen** [microsoft/TaskWeaver#190]
**Describe the bug**

I have defined a plugin with two files but canot use in the taskweaver chat:

1.py file
```
from PyPDF2 import PdfFileWriter, PdfFileReader #裁剪pdf
import fitz #查看pdf内容
from taskweaver.plugin import Plugin, register_plugin
import os

@register_plugin
class GET_PDFFILE(Plugin):
    def __call__(self, task_id: string):
        try:
            root_path = '/work/test_taskweaver/TaskWeaver/project/sample_data/'
            pdf_path = os.path.join(root_path,task_id+'.pdf')
            # Your existing code for creating DataFrame and returning result goes here
            doc = fitz.open(pdf_path)
            page_cnt = doc.pageCount
            return page_cnt,"SUCCESS"
        except Exception as e:
            # Handle exceptions and return an appropriate message
            return None, f"An error occurred: {str(e)}"
```
2.yaml file
```
name: get_pdffile
enabled: true
required: true
description: >-
  get the pdf page numbers of the given task id
examples: |-
  page_count, description = get_pdffile(task_id)

parameters:
  - name: task_id
    type: str
    required: true
    description: >-
      the task_id associated with the pdf to count

returns:
  - name: page_count
    type: int
    description: the page_count of the pdf
  - name: description
    type: str
    description: the status of the code execution
```

**To Reproduce**
1. Start the service
2. Type the user query "xxx"
3. Wait for the response
4. Type the user query "yyy"

**Screenshots**
![192.168.22.227_8161_ (1)](https://picss.sunbangyan.cn/2024/02/05/23806ecbf5e023949ef6ee5c4236a912.jpeg)
![192.168.22.227_8161_ (2)](https://picss.sunbangyan.cn/2024/02/05/69985b252fb8fc938f2fe2a6232da477.jpeg)
![192.168.22.227_8161_ (3)](https://picss.sunbangyan.cn/2024/02/05/3ebc0666dec73ab85c3c4aad49220660.jpeg)
![192.168.22.227_8161_ (4)](https://picdl.sunbangyan.cn/2024/02/05/fc39d6c3e494304c8a6d5959de2c059b.jpeg)

**Environment Information (please complete the following information):**
 - OS: [Linux,]
 - Python Version [ 3.10,]
 - LLM that you're using: [qwen-max]

**Additional context**
