### ISSUE TITLE
`enabled` paramter in `example_planner.yaml` is invalid

### ISSUE THREAD

**Issue by jacky-ch93** [microsoft/TaskWeaver#370]
**Describe the bug**
When I test the multi-planner examples in `project` folder, I found that all the examples used in the prompt no matter if the `enable` parameter is set to `true` or `false`. 
I use the [vllm-openai-compatible-server](https://docs.vllm.ai/en/latest/getting_started/quickstart.html#openai-compatible-server) to peform `llama3` model.
the taskweaver_config is:
```yaml
    "llm.api_type":"openai",
    "llm.api_base": "http://localhost:8233/v1",
    "llm.api_key": "123456",
    "llm.model": "xxx",
    "llm.response_format": "json_object",
```

**To Reproduce**
1. Start the `vllm` service and `python -m  taskweaver -p ./project`

**Environment Information (please complete the following information):**
 - OS: linux
 - Python Version : 3.10
 - LLM that you're using: llama3
