### ISSUE TITLE
Cannot find self defined plugin when executing code

### ISSUE THREAD

**Issue by irmowan** [microsoft/TaskWeaver#423]
I write a plugin under my project/plugins folder:
```python
from taskweaver.plugin import Plugin, register_plugin
from typing import List
try:
    from snownlp import SnowNLP
except ImportError:
    raise ImportError("Please install snownlp with `pip install snownlp`")


@register_plugin
class SentimentAnalysis(Plugin):
    def _init(self) -> None:
        pass

    def sentiment_to_score(self, sentiment: float) -> int:
        """Map (0,1) to 1-5
        """
        return int(sentiment  * 5) + 1

    def __call__(self, inputs: List[str]):
        results = []
        for review in inputs:
            s = SnowNLP(review)
            rating = self.sentiment_to_score(s.sentiments)
            results.append(rating)
        return results    
```
Here is the yaml file:
```yaml
name: sentiment_analysis
enabled: true
required: false
description: >-
  sentiment_analysis processes a list of text inputs and assigns a sentiment score from 1 to 5, based on the polarity of the text.
examples:
  sentiment_scores = sentiment_analysis(["Very good product", "Bad quality", "A little noisy"])

parameters:
  - name: inputs
    type: list
    required: true
    description: >-
      A list of sentences to be analyzed for sentiment polarity.

returns:
  - name: sentiment_scores
    type: list
    description: >-
      A list of sentiment scores (from 1 to 5, integer) for each input string, based on the analysis.
```

However, the taskweaver cannot find this plugin:
![image](https://github.com/user-attachments/assets/4d3afd8d-d1b8-4453-8769-4b1edca01508)

This is the folder structure.
![image](https://github.com/user-attachments/assets/609191e5-06b4-4928-9f8b-38efb51ed1bb)
